---
title: "Comprobación de Conceptos Semana IV"
subtitle: "R con Enfoque Financiero: AulaABA "
output: pdf_document
---

### Selecciona la opción correcta para cada una de las siguientes preguntas.
1. ¿Cuál es el paquete principal de Tidyverse que proporciona una colección de paquetes para el manejo y manipulación de datos en R?
   - [ ] `ggplot2`
   - [ ] `dplyr`
   - [ ] `lubridate`
   - [ ] `tidyr`

2. ¿Qué función de Tidyverse se utiliza para seleccionar columnas específicas de un dataframe?
   - [ ] `mutate()`
   - [ ] `select()`
   - [ ] `filter()`
   - [ ] `arrange()`

3. ¿Cuál de las siguientes funciones de Tidyverse se utiliza para combinar dos o más dataframes en función de una o más columnas clave?
   - [ ] `mutate()`
   - [ ] `filter()`
   - [ ] `join()`
   - [ ] `group_by()`

4. ¿Qué función de Tidyverse se utiliza para calcular resúmenes estadísticos, como la media o la suma, de una columna numérica?
   - [ ] `summarize()`
   - [ ] `arrange()`
   - [ ] `filter()`
   - [ ] `mutate()`

5. ¿Cuál de las siguientes funciones de Tidyverse se utiliza para transformar datos de formato largo (long) a formato ancho (wide)?
   - [ ] `select()`
   - [ ] `pivot_wider()`
   - [ ] `pivot_longer()`
   - [ ] `arrange()`

6. ¿Qué función de Tidyverse se utiliza para agrupar los datos por una o más columnas y realizar operaciones por grupo?
   - [ ] `mutate()`
   - [ ] `arrange()`
   - [ ] `filter()`
   - [ ] `group_by()`

7. ¿Cuál es el paquete de R utilizado para el manejo de fechas y horas?
   - [ ] `stringr`
   - [ ] `dplyr`
   - [ ] `tidyr`
   - [ ] `lubridate`

8. ¿Cuál de las siguientes funciones de "lubridate" se utiliza para convertir una cadena de texto en formato fecha?
   - [ ] `as.numeric()`
   - [ ] `as.character()`
   - [ ] `parse_date()`
   - [ ] `ymd()`

9. ¿Qué función de "lubridate" se utiliza para extraer el año de una fecha?
   - [ ] `hour()`
   - [ ] `minute()`
   - [ ] `day()`
   - [ ] `year()`

10. ¿Cuál de las siguientes funciones de "lubridate" se utiliza para calcular la diferencia en días entre dos fechas?
    - [ ] `dmy()`
    - [ ] `ymd_hms()`
    - [ ] `interval()`
    - [ ] `days()`

11. ¿Qué función de "lubridate" se utiliza para agregar o restar unidades de tiempo a una fecha?
    - [ ] `month()`
    - [ ] `quarter()`
    - [ ] `week()`
    - [ ] `add()`

12. ¿Cuál de las siguientes funciones de "lubridate" se utiliza para extraer el mes de una fecha?
    - [ ] `second()`
    - [ ] `month()`
    - [ ] `as.date()`
    - [ ] `interval()`


1. Respuesta: dplyr
2. Respuesta: select()
3. Respuesta: join()
4. Respuesta: summarize()
5. Respuesta: pivot_wider()
6. Respuesta: group_by()
7. Respuesta: lubridate
8. Respuesta: ymd()
9. Respuesta: year()
10. Respuesta: days()
11. Respuesta: add()
12. Respuesta: month()

