---
title: "Comprobación de Conceptos Semana VI"
subtitle: "R con Enfoque Financiero: AulaABA "
output: pdf_document
---

### Selecciona la opción correcta para cada una de las siguientes preguntas.
1. ¿Cuál es el paquete en R que se utiliza para realizar análisis de rendimiento financiero?
   - [ ] `dplyr`
   - [ ] `tidyverse`
   - [ ] `ggplot2`
   - [ ] `PerformanceAnalytics`

2. ¿Qué función se utiliza en PerformanceAnalytics para calcular el retorno diario de una serie de precios?
   - [ ] `apply.monthly()`
   - [ ] `Return.calculate()`
   - [ ] `chart.RollingPerformance()`
   - [ ] `table.CumReturns()`

3. ¿Cuál es la función en PerformanceAnalytics para calcular la volatilidad de una serie de precios?
   - [ ] `Return.calculate()`
   - [ ] `apply.monthly()`
   - [ ] `chart.RollingPerformance()`
   - [ ] `table.CumReturns()`

4. ¿Qué función se utiliza en PerformanceAnalytics para calcular la matriz de correlación entre múltiples activos financieros?
   - [ ] `table.CumReturns()`
   - [ ] `Return.calculate()`
   - [ ] `apply.monthly()`
   - [ ] `chart.Correlation()`

5. ¿Cuál es la función en PerformanceAnalytics para realizar una descomposición de una serie de precios en sus componentes de tendencia, estacionalidad y residuos?
   - [ ] `Return.calculate()`
   - [ ] `table.CumReturns()`
   - [ ] `chart.Decomposition()`
   - [ ] `apply.monthly()`

6. ¿Qué función se utiliza en PerformanceAnalytics para calcular el ratio de información (Information Ratio) de una estrategia de inversión?
   - [ ] `chart.RollingPerformance()`
   - [ ] `Return.calculate()`
   - [ ] `apply.monthly()`
   - [ ] `InformationRatio()`

7. ¿Cuál es la función en PerformanceAnalytics para realizar un gráfico de evolución del rendimiento de una estrategia de inversión a lo largo del tiempo?
   - [ ] `chart.RollingPerformance()`
   - [ ] `Return.calculate()`
   - [ ] `apply.monthly()`
   - [ ] `chart.TimeSeries()`

8. ¿Qué función se utiliza en PerformanceAnalytics para calcular el Drawdown (reducción) de una estrategia de inversión?
   - [ ] `chart.RollingPerformance()`
   - [ ] `Return.calculate()`
   - [ ] `apply.monthly()`
   - [ ] `table.Drawdowns()`

9. ¿Cuál es la función en PerformanceAnalytics para realizar un gráfico de series de tiempo de múltiples activos financieros?
   - [ ] `chart.RollingPerformance()`
   - [ ] `Return.calculate()`
   - [ ] `apply.monthly()`
   - [ ] `chart.TimeSeries()`

10. ¿Qué función se utiliza en PerformanceAnalytics para calcular el ratio de Sharpe de una estrategia de inversión?
    - [ ] `chart.RollingPerformance()`
    - [ ] `Return.calculate()`
    - [ ] `apply.monthly()`
    - [ ] `SharpeRatio()`

11. ¿Cuál es el paquete en R que se utiliza para el análisis y visualización de datos financieros?
   - [ ] `dplyr`
   - [ ] `tidyverse`
   - [ ] `ggplot2`
   - [ ] `quantmod`

12. ¿Qué función se utiliza en quantmod para descargar datos históricos de precios de acciones?
   - [ ] `getSymbols()`
   - [ ] `read.csv()`
   - [ ] `read.table()`
   - [ ] `fetchData()`

13. ¿Cómo se especifica el símbolo de una acción al usar la función `getSymbols()` en quantmod?
   - [ ] Se especifica como un argumento de cadena de texto.
   - [ ] Se especifica como un argumento numérico.
   - [ ] Se especifica como un argumento lógico.
   - [ ] Se especifica como un argumento de fecha.

14. ¿Cuál es la función en quantmod para trazar un gráfico de la serie de precios de una acción?
   - [ ] `plot()`
   - [ ] `chartSeries()`
   - [ ] `ggplot()`
   - [ ] `lineChart()`

15. ¿Qué función se utiliza en quantmod para calcular los rendimientos diarios de una serie de precios?
   - [ ] `calculateReturns()`
   - [ ] `calculatePerformance()`
   - [ ] `dailyReturns()`
   - [ ] `priceReturns()`

16. ¿Cuál es la función en quantmod para calcular una media móvil simple (SMA) de una serie de precios?
   - [ ] `SMA()`
   - [ ] `EMA()`
   - [ ] `MA()`
   - [ ] `mean()`

17. ¿Qué función se utiliza en quantmod para calcular la desviación estándar de una serie de precios?
   - [ ] `stddev()`
   - [ ] `var()`
   - [ ] `sd()`
   - [ ] `stdev()`

18. ¿Cómo se selecciona un subconjunto de datos en quantmod basado en fechas?
   - [ ] Utilizando la función `subset()`
   - [ ] Utilizando la función `filter()`
   - [ ] Utilizando la función `slice()`
   - [ ] Utilizando la función `subsetData()`

19. ¿Cuál es la función en quantmod para calcular el rendimiento acumulado de una serie de precios?
   - [ ] `cumReturns()`
   - [ ] `totalReturns()`
   - [ ] `TA()`
   - [ ] `returnCumulative()`

20. ¿Qué función se utiliza en quantmod para realizar una regresión lineal entre dos series de precios?
    - [ ] `lm()`
    - [ ] `regression()`
    - [ ] `linearRegression()`
    - [ ] `lineFit()`
  

Respuestas

PerformanceAnalytics
Return.calculate()
Volatility()
chart.Correlation()
chart.Decomposition()
InformationRatio()
chart.RollingPerformance()
table.Drawdowns()
chart.TimeSeries()
SharpeRatio()
quantmod
getSymbols()
Se especifica como un argumento de cadena de texto.
chartSeries()
dailyReturns()
SMA()
sd()
Utilizando la función subset()
cumReturns()
lm()





