---
title: "Comprobación de Conceptos Semana II"
subtitle: "R con Enfoque Financiero: AulaABA "
output: pdf_document
---

## Preguntas

1.  Enumera 5 diferencias entre Tidyverse y Base R:


2. Completa el codigo para multiplicar la columna del rendimiento promedio ponderado por 100 y agrupar el monto total subastado por la columna mesFechaSubasta

```{r}

suppressWarnings(suppressPackageStartupMessages(library(tidyverse)))
##Importacion de datos
letras_bc <- read.table("../../../data/letras_bc_consolidado_clean.csv")

# letras_bc <- letras_bc |>
#  mutate(
#    mesFechaSubasta= month(FechadeSubasta)
#     # Rendimiento Promedio ponderado *100
#    ) |> 
#   group_by( ) |> 
#   summarise()
#   

```



### Selecciona la opción correcta para cada una de las siguientes preguntas.

1.  ¿Cuál de las siguientes opciones es una funcion que nos permite ver los nombres de una columna en base r?

    a.  colnames
    b.  head
    c.  intersect
    d.  numeric

2.  ¿Cuál de las siguientes funciones nos permite concatenar dos dataframes de manera vertical?

    a.  cbind()
    b.  as.DataFrame()
    c.  rbind()
    d.  length()

3.  ¿Qué funcion nos verificar las diferencias entre dos vectores?

    a.  intersect()
    b.  setdiff()
    c.  subset()
    d.  list()

4.  ¿Cuál de las siguientes funciones nos permite determinar el tipo de objeto ?

    a.  merge()
    b.  typeof()
    c.  type()
    d.  cbind()

5.  ¿Como se puede realizar un left join utilizando base R?

    a.  merge(x, y, all.x= FALSE, all.y=TRUE)
    b.  merge(x, y, all.x= TRUE, all.y=TRUE)
    c.  merge(x, y, all.x= TRUE, all.y=FALSE)
    d.  merge(x, y)

6.  ¿Cuál de las siguientes funciones en R tidyverse se utiliza para ver un resumen de las columnas que tiene un dataframe?

    a.  head()
    b.  glimpse()
    c.  mutate()
    d.  summarise()



## Respuestas

a)  colnames
c)  rbind
b)  setdiff()
b)  typeof()
c)  merge(x, y, all.x= TRUE, all.y=FALSE)
b) glimpse()