---
title: "Comprobación de Conceptos Semana III"
subtitle: "R con Enfoque Financiero: AulaABA "
output: pdf_document
---

## Preguntas

1.  Escribe las ventajas de utilizar la funcion list.files() y como se puede combinar con los `for loops`

2.  Describe que esta haciendo la funcion GET en este bloque de codigo.

```{r}
suppressMessages(suppressWarnings(suppressPackageStartupMessages(library(httr))))
suppressMessages(suppressWarnings(suppressPackageStartupMessages(library(readxl))))
linkBC<-  "https://cdn.bancentral.gov.do/documents/estadisticas/mercado-cambiario/documents/TASAS_CONVERTIBLES_OTRAS_MONEDAS.xlsx?v=1684715614947"
GET(linkBC, write_disk(tf <- tempfile(fileext = ".xlsx")))
tipodecambio <-  suppressMessages(suppressWarnings(read_excel(tf)))
```

### Selecciona la opción correcta para cada una de las siguientes preguntas.

1.  ¿Cuál es la función en R para importar datos desde un archivo de Excel?
    -   [ ] `read.table()`
    -   [ ] `read.csv()`
    -   [ ] `read.xlsx()`
    -   [ ] `import.excel()`
2.  ¿Qué paquete de R se utiliza para importar datos desde archivos PDF?
    -   [ ] `readr`
    -   [ ] `tidyr`
    -   [ ] `rvest`
    -   [ ] `pdftools`
3.  ¿Cuál es la forma correcta de importar datos desde un archivo PDF usando el paquete `pdftools`?
    -   [ ] `read_pdf()`
    -   [ ] `import_pdf()`
    -   [ ] `read_pdf_file()`
    -   [ ] `pdf_import()`
4.  ¿Cuál es la función en R para descargar y leer datos directamente desde un enlace web?
    -   [ ] `read.csv()`
    -   [ ] `download.file()`
    -   [ ] `read_html()`
    -   [ ] `import.web()`
5.  ¿Qué paquete de R se utiliza para interactuar con APIs y importar datos en formato JSON?
    -   [ ] `httr`
    -   [ ] `xml2`
    -   [ ] `jsonlite`
    -   [ ] `RCurl`
6.  ¿Cuál es la función en R para realizar solicitudes HTTP y obtener datos de una API?
    -   [ ] `GET()`
    -   [ ] `POST()`
    -   [ ] `REQUEST()`
    -   [ ] `API()`
7.  ¿Cuál es el formato de datos más comúnmente utilizado para intercambiar información con APIs?
    -   [ ] `XML`
    -   [ ] `CSV`
    -   [ ] `JSON`
    -   [ ] `TXT`
8.  ¿Cuál es la función en R para analizar y convertir datos en formato JSON a un objeto de R?
    -   [ ] `fromJSON()`
    -   [ ] `parseJSON()`
    -   [ ] `readJSON()`
    -   [ ] `importJSON()`
9.  ¿Cuál es la forma correcta de establecer una conexión con una API en R utilizando el paquete `httr`?
    -   [ ] `api_connect()`
    -   [ ] `create_connection()`
    -   [ ] `connect_api()`
    -   [ ] `httr::POST()`
10. ¿Cuál es la función en R para acceder a datos específicos dentro de una respuesta JSON de una API?
    -   [ ] `access_json()`
    -   [ ] `extract_json()`
    -   [ ] `parse_json()`
    -   [ ] `json_extract()`
