---
title: "Comprobación de Conceptos Semana VII"
subtitle: "R con Enfoque Financiero: AulaABA "
output: pdf_document
---

### Selecciona la opción correcta para cada una de las siguientes preguntas.

1. ¿Cuál es el paquete en R que se utiliza para realizar análisis de carteras de inversión?
   - [ ] `dplyr`
   - [ ] `tidyverse`
   - [ ] `ggplot2`
   - [ ] `PortfolioAnalytics`

2. ¿Qué función se utiliza en PortfolioAnalytics para crear un objeto de cartera?
   - [ ] `create_portfolio()`
   - [ ] `build_portfolio()`
   - [ ] `portfolio_object()`
   - [ ] `new_portfolio()`

3. ¿Cómo se añaden activos a una cartera en PortfolioAnalytics?
   - [ ] Utilizando la función `add_asset()`
   - [ ] Utilizando la función `add_security()`
   - [ ] Utilizando la función `add_instrument()`
   - [ ] Utilizando la función `add_ticker()`

4. ¿Cuál es la función en PortfolioAnalytics para calcular las estadísticas de rendimiento de una cartera?
   - [ ] `portfolio_stats()`
   - [ ] `calculate_performance()`
   - [ ] `portfolio_performance()`
   - [ ] `calculate_stats()`

5. ¿Qué función se utiliza en PortfolioAnalytics para calcular el rendimiento histórico de una cartera?
   - [ ] `portfolio_returns()`
   - [ ] `calculate_returns()`
   - [ ] `portfolio_performance()`
   - [ ] `calculate_performance()`

6. ¿Cuál es la función en PortfolioAnalytics para calcular la volatilidad de una cartera?
   - [ ] `portfolio_volatility()`
   - [ ] `calculate_volatility()`
   - [ ] `portfolio_risk()`
   - [ ] `calculate_risk()`

7. ¿Cómo se optimiza una cartera en PortfolioAnalytics para encontrar la asignación de activos óptima?
   - [ ] Utilizando la función `optimize_portfolio()`
   - [ ] Utilizando la función `optimize_allocation()`
   - [ ] Utilizando la función `portfolio_optimize()`
   - [ ] Utilizando la función `portfolio_allocation()`

8. ¿Cuál es la función en PortfolioAnalytics para realizar una simulación de montecarlo de una cartera?
   - [ ] `portfolio_monte_carlo()`
   - [ ] `simulate_monte_carlo()`
   - [ ] `portfolio_simulation()`
   - [ ] `simulate_portfolio()`

9. ¿Qué función se utiliza en PortfolioAnalytics para realizar un análisis de riesgo de cola (tail risk) de una cartera?
   - [ ] `portfolio_tail_risk()`
   - [ ] `analyze_tail_risk()`
   - [ ] `calculate_tail_risk()`
   - [ ] `tail_risk_portfolio()`

10. ¿Cómo se realiza una rebalanceo de una cartera en PortfolioAnalytics?
    - [ ] Utilizando la función `rebalance_portfolio()`
    - [ ] Utilizando la función `reallocate_portfolio()`
    - [ ] Utilizando la función `portfolio_rebalance()`
    - [ ] Utilizando la función `portfolio_reallocation()`


Respuestas

PortfolioAnalytics
create_portfolio()
Utilizando la función add_asset()
portfolio_stats()
portfolio_returns()
portfolio_volatility()
Utilizando la función optimize_portfolio()
portfolio_monte_carlo()
portfolio_tail_risk()
Utilizando la función rebalance_portfolio()


