---
title: "Comprobación de Conceptos Semana V"
subtitle: "R con Enfoque Financiero: AulaABA "
output: pdf_document
---

### Selecciona la opción correcta para cada una de las siguientes preguntas.

1. ¿Cuál es el paquete principal en R para la creación de gráficos y visualizaciones de datos?
   - [ ] `tidyverse`
   - [ ] `base`
   - [ ] `ggplot2`
   - [ ] `dplyr`

2. ¿Qué función de ggplot2 se utiliza para crear un gráfico de dispersión (scatter plot)?
   - [ ] `boxplot()`
   - [ ] `hist()`
   - [ ] `barplot()`
   - [ ] `geom_point()`

3. ¿Cuál es la función de ggplot2 que se utiliza para crear un histograma?
   - [ ] `geom_bar()`
   - [ ] `geom_histogram()`
   - [ ] `geom_line()`
   - [ ] `geom_boxplot()`

4. ¿Cuál es la función de ggplot2 que se utiliza para crear un gráfico de barras (bar plot)?
   - [ ] `geom_boxplot()`
   - [ ] `geom_bar()`
   - [ ] `geom_point()`
   - [ ] `geom_line()`

5. ¿Cómo se especifica el eje x en un gráfico de ggplot2?
   - [ ] `labs(x = "Eje X")`
   - [ ] `xlab("Eje X")`
   - [ ] `ylab("Eje X")`
   - [ ] `scale_x_continuous("Eje X")`

6. ¿Cuál es la función de ggplot2 que se utiliza para crear un gráfico de líneas (line plot)?
   - [ ] `geom_bar()`
   - [ ] `geom_boxplot()`
   - [ ] `geom_line()`
   - [ ] `geom_histogram()`

7. ¿Qué función de ggplot2 se utiliza para crear un gráfico de cajas (box plot)?
   - [ ] `geom_bar()`
   - [ ] `geom_point()`
   - [ ] `geom_line()`
   - [ ] `geom_boxplot()`

8. ¿Qué función de ggplot2 se utiliza para crear un gráfico de densidad?
   - [ ] `geom_line()`
   - [ ] `geom_bar()`
   - [ ] `geom_boxplot()`
   - [ ] `geom_density()`

9. ¿Qué función de ggplot2 se utiliza para crear un gráfico de violín?
   - [ ] `geom_bar()`
   - [ ] `geom_point()`
   - [ ] `geom_line()`
   - [ ] `geom_violin()`

10. ¿Qué función de ggplot2 se utiliza para crear un gráfico de área (area plot)?
    - [ ] `geom_bar()`
    - [ ] `geom_point()`
    - [ ] `geom_line()`
    - [ ] `geom_area()`

11. ¿Cómo se especifica el color de los puntos en un gráfico de dispersión de ggplot2?
    - [ ] `color = "blue"`
    - [ ] `fill = "blue"`
    - [ ] `color = "blue" dentro de geom_point()`
    - [ ] `fill = "blue" dentro de geom_point()`

12. ¿Cuál es la función de ggplot2 que se utiliza para crear un gráfico de pastel (pie chart)?
   - [ ] `geom_bar()`
   - [ ] `geom_point()`
   - [ ] `geom_line()`
   - [ ] `geom_pie()`

13. ¿Qué función de ggplot2 se utiliza para crear un gráfico de dispersión con líneas de regresión (scatter plot with regression lines)?
   - [ ] `geom_bar()`
   - [ ] `geom_point()`
   - [ ] `geom_line()`
   - [ ] `geom_smooth()`

14. ¿Cómo se agrega una etiqueta de texto a un gráfico de ggplot2?
   - [ ] `labs(text = "Texto")`
   - [ ] `text_label("Texto")`
   - [ ] `geom_text("Texto")`
   - [ ] `geom_label("Texto")`

15. ¿Qué función de ggplot2 se utiliza para ajustar el tamaño de los puntos en un gráfico de dispersión?
   - [ ] `size_point()`
   - [ ] `scale_point()`
   - [ ] `size()`
   - [ ] `scale_size()`

16. ¿Cómo se guarda un gráfico de ggplot2 en un archivo PNG llamado "plot.png"?
   - [ ] `save_plot("plot.png")`
   - [ ] `export_plot("plot.png")`
   - [ ] `save_png("plot.png")`
   - [ ] `ggsave("plot.png")`


respuestas

ggplot2
geom_point()
geom_histogram()
geom_bar()
xlab("Eje X")
geom_line()
geom_boxplot()
geom_density()
geom_violin()
geom_area()
Mediante el argumento color dentro de la función geom_point()
geom_bar()
geom_smooth()
geom_text("Texto")
size()
ggsave("plot.png")


